### ISSUE TITLE
Seeking doesn't work if 'MOUSE_BTN0	cycle pause' in input.conf

### ISSUE THREAD

**Issue by Drugoy** [torque/mpv-progressbar#34] opened 2017-02-25 17:55 UTC
I have `MOUSE_BTN0	cycle pause` in `input.conf`.
Clicking on the regular seeker works, but with your script it is advised to disable the OSC completely and clicking on your script's seeker - doesn't move the seek position for me.
Could you fix that?

**Comment by torque** [comment] 2017-02-25 18:17
Duplicate of #33.

**Closed by torque** 2017-02-25 18:17 UTC
