### ISSUE TITLE
File name remains visible on startup until mouseover

### ISSUE THREAD

**Issue by rdrr** [torque/mpv-progressbar#11] opened 2016-05-15 15:35 UTC
The filename and track number displayed at the top of the screen is a great addition and works great, except I'm having to move the mouse over the screen to initiate the auto hide functionality.  Otherwise it stays visible the entire time.  The bottom bar begins at it's inactive state.  Pressing TAB does't autohide it (although it works normally on the bottom bar) and it does't matter if the mouse is on the screen or off when started, it is needed to be moved over the screen and then it immediately auto hides.

It would also be great if it were possible to call the title like we can the bottom bar with 'progressbar/request-display'.

**Comment by torque** [comment] 2016-05-15 20:50
What OS are you using? On OS X, I believe this was fixed with mpv-player/mpv#1593, though my personal builds have a couple of other mouse-related patches (which were rejected in mpv-player/mpv#1666) that might affect the behavior. I haven't bothered testing on other OS's due to inconvenience factors, so I'd be interested to know if this is a problem elsewhere.

I can add a little hack to sort of fix this but I'd rather it were fixed in mpv.

Re: the feature request, would you prefer that `request-display` just also show the title or that it be separately bindable? I think the former makes more sense (and is dramatically easier to implement as a bonus).

**Comment by onodera-punpun** [comment] 2016-05-15 21:03
I just double tested this on Linux (using openbox), and I can verify that this problem exists here.

**Comment by torque** [comment] 2016-05-16 02:06
It looks like this still happens on OS X too, sort of. The part that I tried to fix previously was that mpv would report a mouse position of `(0,0)` (i.e. the top-left corner) until the mouse was moved. This may still be the case on other OS's.

I fixed this on OS X but I also clamped the mouse coordinates to the mpv window, so if the mouse is above or below the window, the position will get clamped to one of the hover zones. The real problem is that the `mouse_out` keybinding doesn't fire immediately at startup. It seems that this can be fixed by changing the default behavior to assume the mouse starts off the window, without any obvious downsides.

I hope this will result in better behavior on all platforms, but I'm not sure it'll fix it.

**Comment by onodera-punpun** [comment] 2016-05-16 11:56
The last two commit sadly did not fix this issue for me.

**Comment by rdrr** [comment] 2016-05-16 13:36
I'm on linux (arch) and the fixes now work for me.  Thanks!!

**Comment by onodera-punpun** [comment] 2016-05-16 13:47
Hmm, that's kinda weird, I just checked again and I'm sure it's not working for me. Some info, I'm using openbox with sloppy focus enabled, mpv git master, and the newest libass and ffmpeg (I don't know if this has any influence over the script, but whatever).

**Comment by torque** [comment] 2016-05-28 23:15
The workaround introduced in a141bb88bb7c8f910f9f6eccce1c439dcc50e5c1 might actually help with this if the problem is what I think it is.

**Comment by torque** [comment] 2016-06-09 00:22
I can't reproduce this any more. Reopen if it still happens to you.

**Closed by torque** 2016-06-09 00:22 UTC
Labels: bug, enhancement, mpv bug
